{
 "title": "DelayMeasurement",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Forward Delay",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"DelayValues\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_query_request_count\" or r[\"_measurement\"] == \"http_write_request_bytes\" or r[\"_measurement\"] == \"min-forward-delay\"or r[\"_measurement\"] == \"max-forward-delay\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")"
    }
   ]
  },
  {
   "title": "Backward Delay",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"DelayValues\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_query_request_count\" or r[\"_measurement\"] == \"http_write_request_bytes\" or r[\"_measurement\"] == \"min-backward-delay\" or r[\"_measurement\"] == \"max-backward-delay\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")"
    }
   ]
  },
  {
   "title": "Round Trip Delay",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"DelayValues\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_query_request_count\" or r[\"_measurement\"] == \"http_write_request_bytes\" or r[\"_measurement\"] == \"min-round-trip-delay\" or r[\"_measurement\"] == \"max-round-trip-delay\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")"
    }
   ]
  }
 ]
}